network:
  tcp_ip: "127.0.0.1"
  tcp_port: 5050
  modbus_ip: "127.0.0.1"
  modbus_port: 1502

database:
  name: "filling_data"
  user: "root"
  password: "6637"
  host: "127.0.0.1"
  port: 3306

filling:
  tolerance_limits:
    - 760000  # min tolerance
    - 770000  # max tolerance
  modbus_register: 40001

output_paths:
  q_value_output: "output/q_value_output.txt"
  q_target_output: "output/q_target_output.txt"
  best_action_output: "output/best_action_output.txt"

rl_config:
  gamma: 0.99
  initial_q_value: -125
  learning_rate: 0.01
  exploration_probability: 0.5
  target_state:
    weight: 53
    action: -1
  penalties:
    overflow_scale: -50.0
    underflow_scale: -35.0
  weight_quantization_step: 10000

