algorithm: mab
mode: train
seed: 42
logging_level: INFO
outputs_dir: outputs

data:
  path: data/data.xlsx

training:
  episodes: 2000

hyperparameters:
  alpha: 0.4
  epsilon_start: 0.9
  epsilon_min: 0.1
  epsilon_decay: 0.995
  underflow_penalty_constant: 0.0
  overflow_penalty_constant: 0.0
  safe_min: 74
  safe_max: 76
  starting_switch_point: 45
  exploration_step_weights: [5.0, 4.0, 3.0, 2.0, 1.0]
  

