seed: 42
logging_level: INFO
outputs_dir: outputs

data:
  path: data/data.xlsx

defaults:
  training:
    episodes: 500
  hyperparameters:
    gamma: 0.99
    alpha: 0.01
    initial_q: 0.0
    epsilon_start: 0.9
    epsilon_min: 0.1
    epsilon_decay: 0.995
    underflow_penalty_constant: 0.0
    overflow_penalty_constant: 0.0
    safe_min: 74
    safe_max: 76
    starting_switch_point: 45
    exploration_step_weights: [5.0, 4.0, 3.0, 2.0, 1.0]

experiments:
  - name: zero_penalty
    hyperparameters:
      underflow_penalty_constant: 0.0
      overflow_penalty_constant: 0.0
  - name: low_penalty
    hyperparameters:
      underflow_penalty_constant: -90.0
      overflow_penalty_constant: -90.0
  - name: high_penalty
    hyperparameters:
      underflow_penalty_constant: -3000.0
      overflow_penalty_constant: -3000.0
