algorithm: td
mode: train
seed: 42
logging_level: INFO
outputs_dir: outputs

data:
  path: data/data.xlsx
  sheet_name: null

training:
  episodes: 200
  max_steps_per_episode: 100

hyperparameters:
  alpha: 0.1
  gamma: 0.99
  lambda: 0.8


