algorithm: td
mode: train
seed: 42
logging_level: INFO
outputs_dir: outputs

data:
  path: data/data.xlsx

training:
  episodes: 500

hyperparameters:
  gamma: 0.99
  alpha: 0.1
  initial_q: -125.0
  epsilon_start: 0.5
  epsilon_min: 0.1
  epsilon_decay: 1.0
  underflow_penalty_constant: 0.0
  overflow_penalty_constant: 0.0
  safe_min: 74
  safe_max: 76
  starting_switch_point: 45

